import { transit_realtime } from 'gtfs-realtime-bindings';
import Long from 'long';
import routeHeadsignsData from './route-headsigns.json';

// Route headsigns from GTFS trips.txt (generated by gtfs-mappings.ts)
const routeHeadsigns = routeHeadsignsData as Record<string, { N: string[]; S: string[] }>;

export interface TrainArrival {
  tripId: string;
  routeId: string;
  stopId: string;
  stationId: string; // Parent station ID (without N/S suffix)
  direction: 'N' | 'S'; // N = northbound, S = southbound
  arrivalTime: number; // Unix timestamp in seconds
  arrivalTimeSeconds: number; // Seconds until arrival
  destination: string;
  trainId?: string;
}

export interface ServiceAlert {
  id: string;
  headerText: string;
  descriptionText: string;
  activePeriods: Array<{ start: number; end?: number }>;
  affectedRoutes: string[]; // Route IDs affected by this alert
}

// Helper to convert Long to number
function longToNumber(value: Long | number | string | undefined | null): number {
  if (!value) return 0;
  if (typeof value === 'number') return value;
  if (typeof value === 'string') return parseInt(value, 10);
  if (Long.isLong(value)) return value.toNumber();
  return 0;
}

// Extract parent station ID and direction from stop ID
function parseStopId(stopId: string): { stationId: string; direction: 'N' | 'S' } {
  if (stopId.endsWith('N')) {
    return { stationId: stopId.slice(0, -1), direction: 'N' };
  }
  if (stopId.endsWith('S')) {
    return { stationId: stopId.slice(0, -1), direction: 'S' };
  }
  // If no direction suffix, assume northbound (default)
  return { stationId: stopId, direction: 'N' };
}

// Get headsign for a route and direction from GTFS static data
function getHeadsignForRoute(routeId: string, direction: 'N' | 'S'): string | null {
  const routeHeadsign = routeHeadsigns[routeId];
  if (!routeHeadsign) return null;
  
  const headsigns = direction === 'N' ? routeHeadsign.N : routeHeadsign.S;
  if (headsigns.length === 0) return null;
  
  // Return the first headsign (most common terminal)
  return headsigns[0];
}

export function parseGTFSFeed(
  feedMessage: transit_realtime.FeedMessage,
  targetStopIds: string[],
  routeFilter?: string[]
): {
  arrivals: TrainArrival[];
  alerts: ServiceAlert[];
} {
  const arrivals: TrainArrival[] = [];
  const alerts: ServiceAlert[] = [];

  if (!feedMessage.entity || feedMessage.entity.length === 0) {
    return { arrivals, alerts };
  }

  const targetStopIdSet = new Set(targetStopIds);
  const routeFilterSet = routeFilter ? new Set(routeFilter) : null;

  for (const entity of feedMessage.entity) {
    if (entity.tripUpdate) {
      const tripUpdate = entity.tripUpdate;
      const trip = tripUpdate.trip;
      const routeId = trip?.routeId;
      
      // Filter by route if specified
      if (routeFilterSet && routeId && !routeFilterSet.has(routeId)) {
        continue;
      }

      if (!routeId) continue;

      // Find stop time update for our target stop(s)
      if (tripUpdate.stopTimeUpdate && tripUpdate.stopTimeUpdate.length > 0) {
        for (const stopTimeUpdate of tripUpdate.stopTimeUpdate) {
          // Check if this stop matches any of our target stop IDs
          const stopId = stopTimeUpdate.stopId;
          if (stopId && targetStopIdSet.has(stopId) && stopTimeUpdate.arrival) {
            const arrivalTimeValue = stopTimeUpdate.arrival.time;
            if (!arrivalTimeValue) continue;

            const now = Math.floor(Date.now() / 1000);
            const arrivalTimeSeconds = longToNumber(arrivalTimeValue);
            
            // Only include future arrivals
            if (arrivalTimeSeconds > now) {
              const { stationId, direction } = parseStopId(stopId);
              
              // Extract destination from trip headsign if available
              // Note: GTFS realtime trip descriptor may not always include headsign
              // Fallback to headsign from GTFS static data, then generic direction
              const tripHeadsign = (trip as { tripHeadsign?: string })?.tripHeadsign;
              const destination = tripHeadsign || 
                getHeadsignForRoute(routeId, direction) ||
                (direction === 'N' ? 'Northbound' : 'Southbound');
              
              arrivals.push({
                tripId: trip.tripId || '',
                routeId,
                stopId,
                stationId,
                direction,
                arrivalTime: arrivalTimeSeconds,
                arrivalTimeSeconds: arrivalTimeSeconds - now,
                destination,
                trainId: tripUpdate.vehicle?.label || undefined,
              });
            }
          }
        }
      }
    }

    if (entity.alert) {
      const alert = entity.alert;

      // Collect alerts for any route (or filter if specified)
      const isForRoute = !routeFilterSet || alert.informedEntity?.some(
        (informedEntity) => informedEntity.routeId && routeFilterSet.has(informedEntity.routeId)
      );

      if (isForRoute && alert.headerText && alert.headerText.translation) {
        const translations = alert.headerText.translation;
        if (translations.length > 0) {
          const headerTranslation = translations[0];
          const descriptionTranslations = alert.descriptionText?.translation;
          const descriptionTranslation = descriptionTranslations && descriptionTranslations.length > 0 
            ? descriptionTranslations[0] 
            : null;

          if (headerTranslation?.text) {
            const activePeriods = (alert.activePeriod || []).map((period) => ({
              start: longToNumber(period.start),
              end: period.end ? longToNumber(period.end) : undefined,
            }));

            // Extract affected route IDs from informedEntity
            const affectedRoutes = Array.from(new Set(
              (alert.informedEntity || [])
                .map(ie => ie.routeId)
                .filter((id): id is string => Boolean(id))
            ));

            alerts.push({
              id: entity.id || '',
              headerText: headerTranslation.text,
              descriptionText: descriptionTranslation?.text || '',
              activePeriods,
              affectedRoutes,
            });
          }
        }
      }
    }
  }

  // Sort arrivals by arrival time
  arrivals.sort((a, b) => a.arrivalTime - b.arrivalTime);

  return { arrivals, alerts };
}

export function formatArrivalTime(secondsUntilArrival: number): string {
  if (secondsUntilArrival < 60) {
    return 'Arriving';
  }
  const minutes = Math.floor(secondsUntilArrival / 60);
  return `${minutes} min`;
}

export function formatTime(timestamp: number): string {
  const date = new Date(timestamp * 1000);
  return date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });
}

